# Generated by Django 3.1.6 on 2021-02-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='topUpAmount',
            new_name='transactionAmount',
        ),
    ]
