# Generated by Django 3.2.7 on 2021-09-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntergrationPoint', '0004_usercardregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardregistration',
            name='station',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.RESTRICT, to='IntergrationPoint.stationdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercardregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
    ]
