# Generated by Django 3.2.7 on 2021-09-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0005_auto_20210927_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardregistration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
