# Generated by Django 3.2.7 on 2021-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0006_alter_usercardregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardregistration',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
