# Generated by Django 3.2.7 on 2021-09-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0007_alter_usercardregistration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='IntergrationPoint.usercardregistration')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='IntergrationPoint.stationdetail')),
            ],
        ),
    ]
