# Generated by Django 3.2.7 on 2021-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0008_cardbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbalance',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
