# Generated by Django 3.2.7 on 2021-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0009_cardbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='route_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='route_out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='station_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='station_out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
