# Generated by Django 3.2.7 on 2021-09-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntergrationPoint', '0010_auto_20210927_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='route_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='route_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='station_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='station_out',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
